"use client";

import { useState } from "react";
import { saveCustomDesign } from "../../actions";
import { ShareProfileButton } from "@/components/share-profile-button";

type Design = {
  name: string; slug: string | null; bio: string; avatar_url: string | null; title_style: string; title_color: string; wallpaper_style: string; background_color: string; button_style: string; button_roundness: string; button_color: string; button_text_color: string; page_font: string; text_color: string; custom_footer: string;
};

const fonts = [{ value: "geist", label: "Geist" }, { value: "inter", label: "Inter" }, { value: "poppins", label: "Poppins" }, { value: "playfair", label: "Playfair Display" }, { value: "space", label: "Space Grotesk" }, { value: "dm-sans", label: "DM Sans" }];
const roundness = [{ value: "square", label: "Square" }, { value: "soft", label: "Soft" }, { value: "rounded", label: "Rounded" }, { value: "pill", label: "Pill" }];

export function CustomizeForm({ initial }: { initial: Design }) {
  const [design, setDesign] = useState(initial);
  const set = (key: keyof Design, value: string) => setDesign((current) => ({ ...current, [key]: value }));
  const wallpaper = design.wallpaper_style === "gradient" ? `linear-gradient(135deg, ${design.background_color}, ${design.button_color})` : design.wallpaper_style === "soft" ? `radial-gradient(circle at top, ${design.button_color}, ${design.background_color} 58%)` : design.background_color;

  return <div className="customize-layout">
    <form action={saveCustomDesign} className="customize-form">
      <section className="custom-section"><p className="section-label">Header</p><h2>Profile header</h2><label>Profile image<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp" /></label><label>Title<input name="name" maxLength={60} value={design.name} onChange={(event) => set("name", event.target.value)} /></label><label>Bio<textarea name="bio" maxLength={160} value={design.bio} onChange={(event) => set("bio", event.target.value)} /></label><label>Title style<select name="title_style" value={design.title_style} onChange={(event) => set("title_style", event.target.value)}><option value="normal">Normal</option><option value="uppercase">Uppercase</option><option value="italic">Italic</option><option value="serif">Editorial serif</option></select></label><label>Title color<input name="title_color" type="color" value={design.title_color} onChange={(event) => set("title_color", event.target.value)} /></label></section>
      <section className="custom-section"><p className="section-label">Wallpaper</p><h2>Page background</h2><label>Wallpaper style<select name="wallpaper_style" value={design.wallpaper_style} onChange={(event) => set("wallpaper_style", event.target.value)}><option value="solid">Solid</option><option value="gradient">Gradient</option><option value="soft">Soft glow</option></select></label><label>Background color<input name="background_color" type="color" value={design.background_color} onChange={(event) => set("background_color", event.target.value)} /></label></section>
      <section className="custom-section"><p className="section-label">Buttons</p><h2>Link buttons</h2><label>Button style<select name="button_style" value={design.button_style} onChange={(event) => set("button_style", event.target.value)}><option value="solid">Solid</option><option value="glass">Glass</option><option value="outline">Outline</option></select></label><fieldset><legend>Corner roundness</legend><div className="roundness-options">{roundness.map((item) => <label className={`roundness-${item.value}`} key={item.value}><input type="radio" name="button_roundness" value={item.value} checked={design.button_roundness === item.value} onChange={() => set("button_roundness", item.value)} /><span>{item.label}</span></label>)}</div></fieldset><div className="color-grid"><label>Button color<input name="button_color" type="color" value={design.button_color} onChange={(event) => set("button_color", event.target.value)} /></label><label>Button text<input name="button_text_color" type="color" value={design.button_text_color} onChange={(event) => set("button_text_color", event.target.value)} /></label></div></section>
      <section className="custom-section"><p className="section-label">Text</p><h2>Typography</h2><label>Page font<select name="page_font" value={design.page_font} onChange={(event) => set("page_font", event.target.value)}>{fonts.map((font) => <option value={font.value} key={font.value}>{font.label}</option>)}</select></label><div className="color-grid"><label>Page text<input name="text_color" type="color" value={design.text_color} onChange={(event) => set("text_color", event.target.value)} /></label><label>Title color<input type="color" value={design.title_color} onChange={(event) => set("title_color", event.target.value)} /></label></div></section>
      <section className="custom-section"><p className="section-label">Footer</p><h2>Custom footer</h2><label>Footer text<input name="custom_footer" maxLength={120} value={design.custom_footer} placeholder="Terima kasih sudah berkunjung" onChange={(event) => set("custom_footer", event.target.value)} /></label><small>Footer ini tampil di atas branding LinkHub.</small></section>
      <button className="save-customize">Simpan custom design</button>
    </form>
    <aside className="custom-preview-wrap"><ShareProfileButton slug={design.slug} name={design.name} /><div className={`custom-preview font-${design.page_font}`} style={{ background: wallpaper, color: design.text_color }}><div className="preview-profile">{design.avatar_url ? <span className="preview-photo" style={{ backgroundImage: `url(${design.avatar_url})` }} /> : <div className="preview-avatar">{design.name.slice(0, 1).toUpperCase()}</div>}<h2 className={`title-${design.title_style}`} style={{ color: design.title_color }}>{design.name}</h2><p>{design.bio}</p></div><div className="preview-switch"><button className="active">Links</button><button>Shop</button></div><div className="custom-button-list">{["Instagram", "Portfolio", "YouTube"].map((label) => <span className={`button-${design.button_style} radius-${design.button_roundness}`} style={{ "--button-color": design.button_color, "--button-text": design.button_text_color } as React.CSSProperties} key={label}>{label}<b>↗</b></span>)}</div>{design.custom_footer ? <p className="custom-footer-preview">{design.custom_footer}</p> : null}<footer>LinkHub by Trias</footer></div></aside>
  </div>;
}