"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { login, signup } from "@/app/auth/actions";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { type Locale, withLocale } from "@/lib/i18n";

export function LoginDialog({error,message,signupMode=false,locale}:{error?:string;message?:string;signupMode?:boolean;locale:Locale}){
  const router=useRouter();const en=locale==="en";
  return <Dialog defaultOpen onOpenChange={(open)=>!open&&router.push(withLocale("/",locale))}><DialogContent><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#dfff55] text-lg font-black tracking-[-0.08em] text-[#171712]">LH</div><DialogHeader><DialogTitle>{signupMode?(en?"Create your LinkHub account":"Buat akun LinkHub"):(en?"Welcome back":"Selamat datang kembali")}</DialogTitle><DialogDescription>{signupMode?(en?"Share all your important links from one place.":"Bagikan semua tautan pentingmu dari satu tempat."):(en?"Sign in to manage your Linktree, shop, and insights.":"Masuk untuk mengelola Linktree, toko, dan insight kamu.")}</DialogDescription></DialogHeader>{error?<p className="notice error" role="alert">{error}</p>:null}{message?<p className="notice" role="status">{message}</p>:null}<form action={signupMode?signup:login} className="grid gap-4"><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/>{signupMode?<label className="grid gap-1.5 text-sm font-semibold">{en?"Name":"Nama"}<input autoComplete="name" maxLength={60} name="name" placeholder={en?"Your name":"Nama kamu"} required/></label>:null}<label className="grid gap-1.5 text-sm font-semibold">Email<input autoComplete="email" name="email" placeholder="nama@email.com" required type="email"/></label><label className="grid gap-1.5 text-sm font-semibold">{en?"Password":"Kata sandi"}<input autoComplete={signupMode?"new-password":"current-password"} minLength={8} name="password" placeholder={en?"At least 8 characters":"Minimal 8 karakter"} required type="password"/></label>{!signupMode?<Link className="justify-self-end text-sm font-semibold underline underline-offset-4" href={withLocale("/forgot-password",locale)}>{en?"Forgot password?":"Lupa kata sandi?"}</Link>:null}<button className="mt-1 w-full rounded-xl bg-[#171712] py-3.5 text-white hover:bg-black" type="submit">{signupMode?(en?"Create account":"Buat akun"):(en?"Sign in to dashboard":"Masuk ke dashboard")}</button></form><div className="border-t border-black/10 pt-4 text-center text-sm text-[#68685f]">{signupMode?(en?"Already have an account? ":"Sudah punya akun? "):(en?"Do not have an account? ":"Belum punya akun? ")}<Link className="font-bold text-[#171712] underline decoration-[#dfff55] decoration-4 underline-offset-4" href={withLocale(signupMode?"/login":"/signup",locale)}>{signupMode?(en?"Sign in":"Masuk"):(en?"Sign up free":"Daftar gratis")}</Link></div></DialogContent></Dialog>;
}
