import Link from "next/link";
import { DashboardIcon } from "@/components/dashboard-icon";
import type { Locale } from "@/lib/i18n";

type Day = { key:string; label:string; views:number; clicks:number };
type ClickedLink = { title:string; clicks:number };
type Period = { selected:string; customFrom:string; customTo:string };

export function InsightsDashboard({ totals,days,clickedLinks,period,locale }: { locale:Locale; totals:{views:number;clicks:number;lifetimeViews:number;lifetimeClicks:number};days:Day[];clickedLinks:ClickedLink[];period:Period }) {
  const en=locale==="en";
  const maximum=Math.max(1,...days.flatMap((day)=>[day.views,day.clicks]));
  const clickRate=totals.lifetimeViews?Math.round((totals.lifetimeClicks/totals.lifetimeViews)*100):0;
  return <div className="insights-dashboard">
    <header className="dashboard-topbar"><div><p className="section-label">{en?"My Linktree":"Linktree Saya"}</p><h1>{en?"Insights":"Insight"}</h1></div></header>
    <section className="insight-range" aria-label={en?"Insight date range":"Rentang tanggal insight"}><div className="range-presets">{["1","7","30","90"].map((range)=><Link className={period.selected===range?"active":""} href={`/dashboard/insights?range=${range}`} key={range}>{range} {en?(range==="1"?"day":"days"):"hari"}</Link>)}</div><form><input name="range" type="hidden" value="custom"/><label>{en?"From":"Dari"}<input name="from" type="date" defaultValue={period.customFrom} required/></label><label>{en?"To":"Sampai"}<input name="to" type="date" defaultValue={period.customTo} required/></label><button>{en?"Apply":"Terapkan"}</button></form><div className="export-actions"><Link href="/api/export/insights">{en?"Export insights CSV":"Ekspor insight CSV"}</Link></div></section>
    <section className="primary-metrics"><article><span className="metric-icon"><DashboardIcon name="views"/></span><div><small>{en?"Views":"Tayangan"}</small><strong>{totals.views}</strong></div></article><article><span className="metric-icon"><DashboardIcon name="clicks"/></span><div><small>{en?"Clicks":"Klik"}</small><strong>{totals.clicks}</strong></div></article></section>
    <section className="insight-card activity-card"><div className="card-heading"><div><p className="section-label">{en?"Activity":"Aktivitas"}</p><h2>{en?"Activity overview":"Ringkasan aktivitas"}</h2></div></div>{days.some((day)=>day.views||day.clicks)?<div className="activity-chart">{days.map((day)=><div className="chart-day" key={day.key}><div className="bars"><span className="views-bar" style={{height:`${Math.max(4,(day.views/maximum)*100)}%`}}/><span className="clicks-bar" style={{height:`${Math.max(4,(day.clicks/maximum)*100)}%`}}/></div><small>{day.label}</small></div>)}</div>:<div className="insight-empty"><DashboardIcon name="insights" size={28}/><strong>{en?"No activity during this time":"Tidak ada aktivitas pada periode ini"}</strong><p>{en?"Views and clicks will appear after visitors open your Linktree.":"Tayangan dan klik akan muncul setelah pengunjung membuka Linktree kamu."}</p></div>}</section>
    <div className="insight-columns"><section className="insight-card"><div className="card-heading"><div><p className="section-label">{en?"Most clicked links":"Tautan paling banyak diklik"}</p><h2>{en?"Top links":"Tautan teratas"}</h2></div></div>{clickedLinks.length?<div className="rank-list">{clickedLinks.map((item,index)=><div key={item.title}><span>{index+1}</span><strong>{item.title}</strong><b>{item.clicks}</b></div>)}</div>:<div className="insight-empty compact"><DashboardIcon name="clicks"/><strong>{en?"No clicks during this time":"Tidak ada klik pada periode ini"}</strong></div>}</section><section className="insight-card"><div className="card-heading"><div><p className="section-label">{en?"Linktree visitors":"Pengunjung Linktree"}</p><h2>{en?"Visitor activity":"Aktivitas pengunjung"}</h2></div></div>{days.some((day)=>day.views)?<div className="visitor-list">{days.map((day)=><div key={day.key}><span>{day.label}</span><i><b style={{width:`${Math.max(4,(day.views/maximum)*100)}%`}}/></i><strong>{day.views}</strong></div>)}</div>:<div className="insight-empty compact"><DashboardIcon name="views"/><strong>{en?"No activity during this time":"Tidak ada aktivitas pada periode ini"}</strong></div>}</section></div>
    <section className="lifetime-section"><div><p className="section-label">{en?"Lifetime totals":"Total sepanjang waktu"}</p><h2>{en?"All-time performance":"Performa keseluruhan"}</h2></div><div className="lifetime-grid"><article><DashboardIcon name="views"/><span>{en?"Views":"Tayangan"}</span><strong>{totals.lifetimeViews}</strong></article><article><DashboardIcon name="clicks"/><span>{en?"Clicks":"Klik"}</span><strong>{totals.lifetimeClicks}</strong></article><article><DashboardIcon name="rate"/><span>{en?"Click rate":"Rasio klik"}</span><strong>{clickRate}%</strong></article></div></section>
  </div>;
}